---
title: "Discrete Lakewatch Results "
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("dplyr")
library("ggplot2")
library("grid")
library("ggthemes")
library("lattice")
library("lubridate")
library("marelac")
library("scales")
library("tidyverse")
library("waterData")


```

All discrete measurements were processed by Lakewatch UF on a monthly basis.  
Displayed are the figures for the six sensor sites, spatially arranged in the order they lay near the Lone Cabbage Reef from North to South and West to East.   
Only Sites 1-6 have discrete measurements.  


```{r dataresults, include=FALSE, eval=TRUE}

lab <- read.csv("data/discrete_measurement.csv", header= T)

colnames(lab) <- c("Site", "Date", "Time_org", "Time_UTC", "Sun_code", "Phosphorus", "Nitrogen", "Chlorophyll", "Secchi", "Color", "DO", "Temperature","Conductivity", "Salinity", "Depth", "Sensor_Type")

lab$Secchi<- (lab$Secchi/ 3.28)

lab<- lab %>%
  filter(Sensor_Type == "lakewatch")

lab$Date <- as.POSIXct(as.Date(lab$Date,origin= "1899-12-30"))

lab$facet = factor(lab$Site, levels = c("6", "1", "5", "2","4", "3"))

```


```{r dis, warning= FALSE,  message=FALSE, results="hide" , include=FALSE}

#Station to analyze, can be changed to another station
station = '02323500'   

#Get site name to use in plot titles and such
stinfo  = siteInfo(station)

#Read entire time series, might take several minutes
dis   = importDVs(staid=station,code='00060',stat='00003', sdate= "1950-01-01") 

#Getting some date components
dis$year    = as.numeric(strftime(dis$dates,format="%Y"))
dis$month   = as.numeric(strftime(dis$dates,format="%m")) 

```

```{r discol, warning= FALSE,  message=FALSE, results="hide", include=FALSE}

#Naming columns, using the Diver sensors, collects date, pressure, temp, conductivity
colnames(dis) <- c("StaID", "Discharge", "oldDate", "QualCode", "Year", "Month")
head(dis)

#Changing the format of the dates to be able to plot against time
dis$Date <- as.POSIXct(as.Date(dis$oldDate,origin= "1899-12-30"))

```

```{r phos, warning=FALSE, echo=FALSE, message=FALSE,fig.width=10,fig.height=9}
  
ggplot(data= lab, aes(x= Date)) +
  ggtitle("Phosphorus") +
  ylab ("Phosphorus(µg/L)") +
  geom_line(data= dis, aes(y=Discharge/160), color= "cornflowerblue", size=2, alpha=0.8) +
  geom_point(aes(y= Phosphorus), size=3) +
  scale_y_continuous(sec.axis = sec_axis(~.*160, name = "River Discharge (cfs)"), limits=c(0,125)) + 
  scale_x_datetime(
    breaks = date_breaks("4 weeks") ,
    labels = date_format("%Y/%m"),
    expand = c(0, 0),
    limits = c(
      as.POSIXct("2017-08-10"),
      as.POSIXct("2018-05-30"))) +
  theme_bw()+
  theme(legend.position=("top"),
        panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
        panel.border = element_rect(color = "black", size = 1, fill = NA, linetype="solid"),
        axis.text=element_text(size=20),
        axis.title=element_text(size=20,face="bold"),
        plot.title =element_text(size=30, face='bold'),
        axis.text.x = element_text(angle = 90, hjust = 1)) +
  facet_wrap(~facet, ncol= 2)
```
<br>
<br>
```{r nitrogen, warning=FALSE, echo=FALSE, message=FALSE,fig.width=10,fig.height=9}
ggplot(data= lab, aes(x= Date)) +
  ggtitle("Nitrogen")+
  ylab ("Nitrogen(µg/L)") +
  geom_line(data= dis, aes(y=Discharge/13), color= "cornflowerblue", size=2, alpha=0.8) +
  geom_point(aes(y= Nitrogen), size=3) +
  scale_y_continuous(sec.axis = sec_axis(~.*13, name = "River Discharge (cfs)"), limits=c(0,1500)) + 
  scale_x_datetime(
    breaks = date_breaks("4 weeks") ,
    labels = date_format("%Y/%m"),
    expand = c(0, 0),
    limits = c(
      as.POSIXct("2017-08-10"),
      as.POSIXct("2018-05-30")))+
  theme_bw()+
  theme(legend.position=("top"),
        panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
        panel.border = element_rect(color = "black", size = 1, fill = NA, linetype="solid"),
        axis.text=element_text(size=20),
        axis.title=element_text(size=20,face="bold"),
        plot.title =element_text(size=30, face='bold'),
        axis.text.x = element_text(angle = 90, hjust = 1)) +
  facet_wrap(~facet, ncol= 2)
```
<br>
<br>
```{r chlorophyll, warning=FALSE, echo=FALSE, message=FALSE,fig.width=10,fig.height=9}
ggplot(data= lab, aes(x= Date)) +
  ggtitle("Chlorophyll")+
  ylab ("Chlorophyll(µg/L)") +
  geom_line(data= dis, aes(y=Discharge/250), color= "cornflowerblue", size=2, alpha=0.8) +
  geom_point(aes(y= Chlorophyll), size=3) +
  scale_y_continuous(sec.axis = sec_axis(~.*250, name = "River Discharge (cfs)"), limits=c(0,80)) + 
  scale_x_datetime(
    breaks = date_breaks("4 weeks") ,
    labels = date_format("%Y/%m"),
    expand = c(0, 0),
    limits = c(
      as.POSIXct("2017-08-10"),
      as.POSIXct("2018-05-30"))) +
  theme_bw()+
  theme(legend.position=("top"),
        panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
        panel.border = element_rect(color = "black", size = 1, fill = NA, linetype="solid"),
        axis.text=element_text(size=20),
        axis.title=element_text(size=20,face="bold"),
        plot.title =element_text(size=30, face='bold'),
        axis.text.x = element_text(angle = 90, hjust = 1)) +
  facet_wrap(~facet, ncol= 2)
```
<br>
<br>
```{r color, warning=FALSE, echo=FALSE, message=FALSE,fig.width=10,fig.height=9}
ggplot(data= lab, aes(x= Date)) +
  ggtitle("Color") +
  ylab ("Color(Pt-Co Units)") +
  geom_line(data= dis, aes(y=Discharge/160), color= "cornflowerblue", size=2, alpha=0.8) +
  geom_point(aes(y= Color), size=3) +
  scale_y_continuous(sec.axis = sec_axis(~.*160, name = "River Discharge (cfs)"), limits=c(0,125)) + 
  scale_x_datetime(
    breaks = date_breaks("4 weeks") ,
    labels = date_format("%Y/%m"),
    expand = c(0, 0),
    limits = c(
      as.POSIXct("2017-08-10"),
      as.POSIXct("2018-05-30"))) +
  theme_bw()+
  theme(legend.position=("top"),
        panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
        panel.border = element_rect(color = "black", size = 1, fill = NA, linetype="solid"),
        axis.text=element_text(size=20),
        axis.title=element_text(size=20,face="bold"),
        plot.title =element_text(size=30, face='bold'),
        axis.text.x = element_text(angle = 90, hjust = 1)) +
  facet_wrap(~facet, ncol= 2)
```
<br>
<br>
```{r secchi, warning=FALSE, echo=FALSE, message=FALSE,fig.width=10,fig.height=9}
ggplot(data= lab, aes(x= Date)) +
  ggtitle("Secchi") +
  ylab ("Secchi (ft)") +
  geom_line(data= dis, aes(y=Discharge/10000), color= "cornflowerblue", size=2, alpha=0.8) +
  geom_point(aes(y= Secchi), size=3) +
  scale_y_continuous(sec.axis = sec_axis(~.*10000, name = "River Discharge (cfs)"), limits=c(0,2)) + 
  scale_x_datetime(
    breaks = date_breaks("4 weeks") ,
    labels = date_format("%Y/%m"),
    expand = c(0, 0),
    limits = c(
      as.POSIXct("2017-08-10"),
      as.POSIXct("2018-05-30"))) +
  theme_bw()+
  theme(legend.position=("top"),
        panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
        panel.border = element_rect(color = "black", size = 1, fill = NA, linetype="solid"),
        axis.text=element_text(size=20),
        axis.title=element_text(size=20,face="bold"),
        plot.title =element_text(size=30, face='bold'),
        axis.text.x = element_text(angle = 90, hjust = 1)) +
  facet_wrap(~facet, ncol= 2)
```
<br>
<br>
```{r cond, warning=FALSE, echo=FALSE, message=FALSE,fig.width=10,fig.height=9}
ggplot(data= lab, aes(x= Date)) +
  ggtitle("Conductivity") +
  ylab ("Conductivity (mS/cm)") +
  geom_line(data= dis, aes(y=Discharge/500), color= "cornflowerblue", size=2, alpha=0.8) +
  geom_point(aes(y= Conductivity), size=3) +
  scale_y_continuous(sec.axis = sec_axis(~.*500, name = "River Discharge (cfs)"), limits=c(0,40)) + 
  scale_x_datetime(
    breaks = date_breaks("4 weeks") ,
    labels = date_format("%Y/%m"),
    expand = c(0, 0),
    limits = c(
      as.POSIXct("2017-08-10"),
      as.POSIXct("2018-05-30"))) +
  theme_bw()+
  theme(legend.position=("top"),
        panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
        panel.border = element_rect(color = "black", size = 1, fill = NA, linetype="solid"),
        axis.text=element_text(size=20),
        axis.title=element_text(size=20,face="bold"),
        plot.title =element_text(size=30, face='bold'),
        axis.text.x = element_text(angle = 90, hjust = 1)) +
  facet_wrap(~facet, ncol= 2)
```




